server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:8888
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
           - Path=/order/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
           - Path=/product/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true


