version: '3'

services:

  service-registry:
    image: 'park05218/service-registry:0.0.1'
    container_name: service-registry
    ports:
      - '8761:8761'
  
  config-server:
    image: 'park05218/config-server:0.0.1'
    container_name: config-server
    ports:
      - '8888:8888'
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-registry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - service-registry  

  product-service:
    image: 'park05218/product-service:0.0.1'
    container_name: product-service
    ports:
      - '8080:8080'
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-registry:8761/eureka
      - CONFIG_SERVER_URL=config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://product-service:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5  
    depends_on:
      config-server:
        condition: service_healthy

  order-service:
    image: 'park05218/order-service:0.0.1'
    container_name: order-service
    ports:
      - '8081:8081'
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-registry:8761/eureka
      - CONFIG_SERVER_URL=config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://order-service:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5  
    depends_on:
      config-server:
        condition: service_healthy

  api-gateway:
    image: 'park05218/api-gateway:0.0.1'
    container_name: api-gateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-registry:8761/eureka
      - CONFIG_SERVER_URL=config-server
    depends_on:
      product-service:
        condition: service_healthy
      order-service:
        condition: service_healthy        

