version: '3'
services:
  api-gateway:
    image: 'park05218/api-gateway:0.0.1'
    container_name: api-gateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - CONFIG_SERVER_URL=host.docker.internal